In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('https://raw.githubusercontent.com/Shivan118/New-Machine-Learning-Modular-Coding-projecs/refs/heads/main/Data/finalTrain.csv')

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [5]:
df = df.drop(columns=["ID","Delivery_person_ID"],axis=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_Age          43730 non-null  float64
 1   Delivery_person_Ratings      43676 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Order_Date                   45584 non-null  object
 7   Time_Orderd                  43853 non-null  object
 8   Time_Order_picked            45584 non-null  object
 9   Weather_conditions           44968 non-null  object
 10  Road_traffic_density         44983 non-null  object
 11  Vehicle_condition            45584 non-null  int64
 12  Type_of_order                45584 non-null  object
 13  Type_of_vehicle              45584 non-null  object
 14  multiple_deliveries          44591 non-null  float64
 15  Festival                     45356 non-null  object
 16  City                         44384 non-null  object
 17  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(9)
memory usage: 6.3+ MB

In [7]:
df.to_csv('raw.csv', index=False)

In [8]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"],format="%d-%m-%Y")

In [9]:
df["Order_Date"]

0       2022-02-12
1       2022-02-13
2       2022-03-04
3       2022-02-13
4       2022-02-14
           ...
45579   2022-03-24
45580   2022-02-16
45581   2022-03-11
45582   2022-03-07
45583   2022-03-02
Name: Order_Date, Length: 45584, dtype: datetime64[ns]

In [10]:
df["day"]=df["Order_Date"].dt.day
df["month"]=df["Order_Date"].dt.month
df["year"]=df["Order_Date"].dt.year 
df.drop("Order_Date",axis=1,inplace=True)

In [11]:
df.dropna(subset="Time_Orderd",inplace=True)

In [12]:
def extract_time(x):
    try:
        return x.split(":")[0]+':'+x.split(':')[1][:2]
    except IndexError:
        return "00:00"

In [13]:
df["Time_Orderd"] = pd.to_datetime(df["Time_Orderd"], format="%H:%M", errors="coerce")

df["Timeorder_hour"] = df["Time_Orderd"].dt.hour
df["Timeorder_minute"] = df["Time_Orderd"].dt.minute

# Convert to int safely (handles NaN)
df["Timeorder_hour"] = df["Timeorder_hour"].fillna(0).astype(int)
df["Timeorder_minute"] = df["Timeorder_minute"].fillna(0).astype(int)

In [14]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,...,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),day,month,year,Timeorder_hour,Timeorder_minute
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,1900-01-01 21:55:00,22:10,Fog,Jam,...,motorcycle,3.0,No,Metropolitian,46,12,2,2022,21,55
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1900-01-01 14:55:00,15:05,Stormy,High,...,motorcycle,1.0,No,Metropolitian,23,13,2,2022,14,55
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,1900-01-01 17:30:00,17:40,Sandstorms,Medium,...,scooter,1.0,No,Metropolitian,21,4,3,2022,17,30
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,1900-01-01 09:20:00,09:30,Sandstorms,Low,...,motorcycle,0.0,No,Metropolitian,20,13,2,2022,9,20
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,1900-01-01 19:50:00,20:05,Fog,Jam,...,scooter,1.0,No,Metropolitian,41,14,2,2022,19,50

In [15]:
df["Weather_conditions"].value_counts()

Weather_conditions
Fog           7475
Stormy        7400
Cloudy        7336
Sandstorms    7284
Windy         7251
Sunny         7107
Name: count, dtype: int64

In [16]:
x=pd.get_dummies(df["Weather_conditions"])

In [17]:
# df = pd.concat([df,x],axis=1).head()

In [18]:
df.head(100)

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,...,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),day,month,year,Timeorder_hour,Timeorder_minute
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,1900-01-01 21:55:00,22:10,Fog,Jam,...,motorcycle,3.0,No,Metropolitian,46,12,2,2022,21,55
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1900-01-01 14:55:00,15:05,Stormy,High,...,motorcycle,1.0,No,Metropolitian,23,13,2,2022,14,55
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,1900-01-01 17:30:00,17:40,Sandstorms,Medium,...,scooter,1.0,No,Metropolitian,21,4,3,2022,17,30
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,1900-01-01 09:20:00,09:30,Sandstorms,Low,...,motorcycle,0.0,No,Metropolitian,20,13,2,2022,9,20
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,1900-01-01 19:50:00,20:05,Fog,Jam,...,scooter,1.0,No,Metropolitian,41,14,2,2022,19,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,23.0,4.8,18.994237,72.825553,19.104237,72.935553,1900-01-01 22:35:00,22:40,Cloudy,Low,...,scooter,1.0,No,Urban,22,18,3,2022,22,35
98,21.0,4.3,12.284747,76.625861,12.414747,76.755861,1900-01-01 20:10:00,20:20,Fog,Jam,...,scooter,0.0,No,Metropolitian,42,23,3,2022,20,10
99,27.0,4.7,21.175975,72.795503,21.195975,72.815503,1900-01-01 10:55:00,11:10,Sandstorms,Low,...,scooter,0.0,No,Urban,12,15,3,2022,10,55
100,32.0,4.2,11.000762,76.981876,11.130762,77.111876,1900-01-01 20:35:00,20:45,Cloudy,Jam,...,motorcycle,1.0,No,Metropolitian,38,8,3,2022,20,35
101,25.0,4.6,21.173343,72.792731,21.283343,72.902731,1900-01-01 23:20:00,23:35,Sunny,Low,...,motorcycle,1.0,No,Metropolitian,23,10,3,2022,23,20

In [19]:
df["Road_traffic_density"].value_counts()

Road_traffic_density
Low       15061
Jam       13796
Medium    10676
High       4320
Name: count, dtype: int64

In [20]:
df.dropna(subset=["Road_traffic_density"],inplace=True)

In [21]:
df["Road_traffic_density"]=df["Road_traffic_density"].map({"Low":1,"Medium":2,"High":3,"Jam":4}).astype(int)

In [22]:
df

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,...,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),day,month,year,Timeorder_hour,Timeorder_minute
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,1900-01-01 21:55:00,22:10,Fog,4,...,motorcycle,3.0,No,Metropolitian,46,12,2,2022,21,55
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1900-01-01 14:55:00,15:05,Stormy,3,...,motorcycle,1.0,No,Metropolitian,23,13,2,2022,14,55
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,1900-01-01 17:30:00,17:40,Sandstorms,2,...,scooter,1.0,No,Metropolitian,21,4,3,2022,17,30
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,1900-01-01 09:20:00,09:30,Sandstorms,1,...,motorcycle,0.0,No,Metropolitian,20,13,2,2022,9,20
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,1900-01-01 19:50:00,20:05,Fog,4,...,scooter,1.0,No,Metropolitian,41,14,2,2022,19,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,30.0,4.8,26.902328,75.794257,26.912328,75.804257,1900-01-01 11:35:00,11:45,Windy,3,...,motorcycle,0.0,No,Metropolitian,32,24,3,2022,11,35
45580,21.0,4.6,0.000000,0.000000,0.070000,0.070000,1900-01-01 19:55:00,20:10,Windy,4,...,motorcycle,1.0,No,Metropolitian,36,16,2,2022,19,55
45581,30.0,4.9,13.022394,80.242439,13.052394,80.272439,1900-01-01 23:50:00,24:05:00,Cloudy,1,...,scooter,0.0,No,Metropolitian,16,11,3,2022,23,50
45582,20.0,4.7,11.001753,76.986241,11.041753,77.026241,1900-01-01 13:35:00,13:40,Cloudy,3,...,motorcycle,1.0,No,Metropolitian,26,7,3,2022,13,35
45583,23.0,4.9,23.351058,85.325731,23.431058,85.405731,1900-01-01 17:10:00,17:15,Fog,2,...,scooter,1.0,No,Metropolitian,36,2,3,2022,17,10

In [23]:
df["Type_of_vehicle"].value_counts()

Type_of_vehicle
motorcycle          25627
scooter             14692
electric_scooter     3534
Name: count, dtype: int64

In [24]:
x = pd.get_dummies(df["Weather_conditions"],drop_first=True)
df = pd.concat([df,x],axis=1)
df.drop("Weather_conditions",axis=1,inplace=True)

In [25]:
df["Type_of_vehicle"]=df["Type_of_vehicle"].map({"electric_scooter":1,"scooter":2,"motorcycle":3,"bicycle":4}).astype(int)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43853 entries, 0 to 45583
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_Age          43639 non-null  float64
 1   Delivery_person_Ratings      43585 non-null  float64
 2   Restaurant_latitude          43853 non-null  float64
 3   Restaurant_longitude         43853 non-null  float64
 4   Delivery_location_latitude   43853 non-null  float64
 5   Delivery_location_longitude  43853 non-null  float64
 6   Time_Orderd                  39785 non-null  datetime64[ns]
 7   Time_Order_picked            43853 non-null  object
 8   Road_traffic_density         43853 non-null  int64
 9   Vehicle_condition            43853 non-null  int64
 10  Type_of_order                43853 non-null  object
 11  Type_of_vehicle              43853 non-null  int64
 12  multiple_deliveries          42910 non-null  float64
 13  Festival                     43634 non-null  object
 14  City                         42709 non-null  object
 15  Time_taken (min)             43853 non-null  int64
 16  day                          43853 non-null  int32
 17  month                        43853 non-null  int32
 18  year                         43853 non-null  int32
 19  Timeorder_hour               43853 non-null  int64
 20  Timeorder_minute             43853 non-null  int64
 21  Fog                          43853 non-null  bool
 22  Sandstorms                   43853 non-null  bool
 23  Stormy                       43853 non-null  bool
 24  Sunny                        43853 non-null  bool
 25  Windy                        43853 non-null  bool
dtypes: bool(5), datetime64[ns](1), float64(7), int32(3), int64(6), object(4)
memory usage: 7.1+ MB

In [39]:
df.isnull().sum()

Delivery_person_Age               0
Delivery_person_Ratings           0
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Time_Orderd                       0
Time_Order_picked              4359
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                           1017
Time_taken (min)                  0
day                               0
month                             0
year                              0
Timeorder_hour                    0
Timeorder_minute                  0
Fog                               0
Sandstorms                        0
Stormy                            0
Sunny                             0
Windy                             0
dtype: int64

In [28]:
df["Festival"].value_counts()

Festival
No     42777
Yes      857
Name: count, dtype: int64

In [29]:
df.dropna(subset=["Festival"],inplace=True)

In [30]:
df.dropna(subset=["Time_Orderd"],inplace=True)

In [31]:
df["Festival"]=df["Festival"].map({"No":0,"Yes":1}).astype(int)

In [32]:
df["multiple_deliveries"].value_counts()

multiple_deliveries
1.0    24480
0.0    12207
2.0     1744
3.0      313
Name: count, dtype: int64

In [33]:
df["multiple_deliveries"]=df["multiple_deliveries"].fillna(0).astype(int)

In [34]:
df["Time_Order_picked"] = pd.to_datetime(df["Time_Order_picked"], format="%H:%M", errors="coerce")

In [35]:
df["Delivery_person_Age"]=df["Delivery_person_Age"].fillna(df["Delivery_person_Age"].median()).astype(int)

In [36]:
df["Delivery_person_Ratings"]=df["Delivery_person_Ratings"].fillna(df["Delivery_person_Ratings"].median())

In [37]:
df["City"].value_counts()

City
Metropolitian    29656
Urban             8770
Semi-Urban         148
Name: count, dtype: int64

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39591 entries, 0 to 45583
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_Age          39591 non-null  int64
 1   Delivery_person_Ratings      39591 non-null  float64
 2   Restaurant_latitude          39591 non-null  float64
 3   Restaurant_longitude         39591 non-null  float64
 4   Delivery_location_latitude   39591 non-null  float64
 5   Delivery_location_longitude  39591 non-null  float64
 6   Time_Orderd                  39591 non-null  datetime64[ns]
 7   Time_Order_picked            35232 non-null  datetime64[ns]
 8   Road_traffic_density         39591 non-null  int64
 9   Vehicle_condition            39591 non-null  int64
 10  Type_of_order                39591 non-null  object
 11  Type_of_vehicle              39591 non-null  int64
 12  multiple_deliveries          39591 non-null  int64
 13  Festival                     39591 non-null  int64
 14  City                         38574 non-null  object
 15  Time_taken (min)             39591 non-null  int64
 16  day                          39591 non-null  int32
 17  month                        39591 non-null  int32
 18  year                         39591 non-null  int32
 19  Timeorder_hour               39591 non-null  int64
 20  Timeorder_minute             39591 non-null  int64
 21  Fog                          39591 non-null  bool
 22  Sandstorms                   39591 non-null  bool
 23  Stormy                       39591 non-null  bool
 24  Sunny                        39591 non-null  bool
 25  Windy                        39591 non-null  bool
dtypes: bool(5), datetime64[ns](2), float64(5), int32(3), int64(9), object(2)
memory usage: 6.4+ MB